// Generated by CoffeeScript 2.2.3
(function() {
  var CronJob, CronTime, SunCalc, SunCronJob;

  ({CronJob, CronTime} = require('cron'));

  SunCalc = require('suncalc');

  SunCronJob = class SunCronJob {
    constructor(params) {
      var defaults, delay, ref;
      defaults = {
        latitude: 51.4826,
        longitude: 0,
        hours: 0,
        minutes: 0,
        seconds: 0,
        offset: 'before',
        riseset: 'sunrise',
        once: false
      };
      Object.assign(this, defaults, params);
      delay = (((this.hours * 60) + this.minutes) * 60 + this.seconds) * 1000;
      // delay is milliseconds after
      this.delay = (function() {
        switch (this.offset) {
          case 'before':
            return -delay;
          case 'after':
            return delay;
          default:
            throw new TypeError('offset must be "before" or "after"');
        }
      }).call(this);
      if ((ref = this.riseset) !== 'sunrise' && ref !== 'sunset') {
        throw new TypeError('riseset must be "sunrise" or "sunset"');
      }
      this.cronTime = this.next();
      this.onComplete = this.once ? () => {
        var running;
        if (typeof params.onComplete === "function") {
          params.onComplete();
        }
        return running = false;
      } : () => {
        if (typeof params.onComplete === "function") {
          params.onComplete();
        }
        this.cronTime = this.next();
        return this.job = new CronJob(this);
      };
      this.job = new CronJob(this);
    }

    next(date = new Date()) {
      var time, times;
      times = SunCalc.getTimes(date, this.latitude, this.longitude);
      time = new Date(times[this.riseset].valueOf() + this.delay);
      if (time <= new Date) {
        date.setDate(date.getDate() + 1);
        return this.next(date);
      } else {
        return time;
      }
    }

    start() {
      this.job.start();
      return this.running = true;
    }

    stop() {
      this.job.stop();
      return this.running = false;
    }

  };

  module.exports = SunCronJob;

}).call(this);
